# Generated by Django 4.2.25 on 2025-11-16 00:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE realtime_dj_djsession (
                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                dj_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                station_id UUID REFERENCES stations(id) ON DELETE CASCADE,
                session_name VARCHAR(255) NOT NULL,
                description TEXT DEFAULT '',
                started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                ended_at TIMESTAMPTZ,
                is_live BOOLEAN NOT NULL DEFAULT false,
                is_recording BOOLEAN NOT NULL DEFAULT false,
                sample_rate INTEGER NOT NULL DEFAULT 48000,
                bit_depth INTEGER NOT NULL DEFAULT 16,
                channels INTEGER NOT NULL DEFAULT 2,
                current_listeners INTEGER NOT NULL DEFAULT 0,
                peak_listeners INTEGER NOT NULL DEFAULT 0,
                master_level_left FLOAT NOT NULL DEFAULT 0.0,
                master_level_right FLOAT NOT NULL DEFAULT 0.0,
                channel_a_level FLOAT NOT NULL DEFAULT 0.0,
                channel_b_level FLOAT NOT NULL DEFAULT 0.0,
                crossfader_position FLOAT NOT NULL DEFAULT 0.0,
                master_volume FLOAT NOT NULL DEFAULT 0.8,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS realtime_dj_djsession CASCADE;"
        ),
        migrations.RunSQL(
            """
            CREATE TABLE realtime_dj_djtrackinstance (
                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                session_id UUID NOT NULL REFERENCES realtime_dj_djsession(id) ON DELETE CASCADE,
                track_id UUID,
                track_title VARCHAR(255) NOT NULL,
                track_artist VARCHAR(255) NOT NULL,
                track_duration FLOAT,
                deck VARCHAR(1) NOT NULL CHECK (deck IN ('A', 'B')),
                started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                ended_at TIMESTAMPTZ,
                current_position FLOAT NOT NULL DEFAULT 0.0,
                playback_speed FLOAT NOT NULL DEFAULT 1.0,
                is_playing BOOLEAN NOT NULL DEFAULT false,
                is_looping BOOLEAN NOT NULL DEFAULT false,
                volume FLOAT NOT NULL DEFAULT 0.8,
                eq_low FLOAT NOT NULL DEFAULT 0.0,
                eq_mid FLOAT NOT NULL DEFAULT 0.0,
                eq_high FLOAT NOT NULL DEFAULT 0.0,
                detected_bpm FLOAT,
                manual_bpm FLOAT,
                is_synced BOOLEAN NOT NULL DEFAULT false,
                cue_points JSONB NOT NULL DEFAULT '{}',
                hot_cues JSONB NOT NULL DEFAULT '{}',
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS realtime_dj_djtrackinstance CASCADE;"
        ),
        migrations.RunSQL(
            """
            CREATE TABLE realtime_dj_audiolevelsnapshot (
                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                session_id UUID NOT NULL REFERENCES realtime_dj_djsession(id) ON DELETE CASCADE,
                timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                master_left FLOAT NOT NULL,
                master_right FLOAT NOT NULL,
                master_peak_left FLOAT NOT NULL,
                master_peak_right FLOAT NOT NULL,
                channel_a_left FLOAT NOT NULL,
                channel_a_right FLOAT NOT NULL,
                channel_b_left FLOAT NOT NULL,
                channel_b_right FLOAT NOT NULL,
                channel_a_peak FLOAT NOT NULL,
                channel_b_peak FLOAT NOT NULL,
                frequency_data JSONB
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS realtime_dj_audiolevelsnapshot CASCADE;"
        ),
        migrations.RunSQL(
            """
            CREATE TABLE realtime_dj_djmixerstate (
                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                session_id UUID NOT NULL REFERENCES realtime_dj_djsession(id) ON DELETE CASCADE,
                crossfader FLOAT NOT NULL DEFAULT 0.0,
                master_volume FLOAT NOT NULL DEFAULT 0.8,
                channel_a_volume FLOAT NOT NULL DEFAULT 0.8,
                channel_a_eq_low FLOAT NOT NULL DEFAULT 0.0,
                channel_a_eq_mid FLOAT NOT NULL DEFAULT 0.0,
                channel_a_eq_high FLOAT NOT NULL DEFAULT 0.0,
                channel_a_filter FLOAT NOT NULL DEFAULT 0.0,
                channel_b_volume FLOAT NOT NULL DEFAULT 0.8,
                channel_b_eq_low FLOAT NOT NULL DEFAULT 0.0,
                channel_b_eq_mid FLOAT NOT NULL DEFAULT 0.0,
                channel_b_eq_high FLOAT NOT NULL DEFAULT 0.0,
                channel_b_filter FLOAT NOT NULL DEFAULT 0.0,
                bpm_master FLOAT,
                sync_enabled BOOLEAN NOT NULL DEFAULT false,
                effects_active JSONB NOT NULL DEFAULT '{}',
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS realtime_dj_djmixerstate CASCADE;"
        ),
        migrations.RunSQL(
            """
            CREATE TABLE realtime_dj_livestreammetrics (
                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                session_id UUID NOT NULL REFERENCES realtime_dj_djsession(id) ON DELETE CASCADE,
                timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                current_listeners INTEGER NOT NULL DEFAULT 0,
                unique_listeners INTEGER NOT NULL DEFAULT 0,
                bitrate INTEGER NOT NULL,
                dropped_frames INTEGER NOT NULL DEFAULT 0,
                buffer_health FLOAT NOT NULL DEFAULT 1.0,
                bandwidth_usage BIGINT NOT NULL,
                latency FLOAT,
                listener_locations JSONB
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS realtime_dj_livestreammetrics CASCADE;"
        ),
        migrations.RunSQL(
            """
            CREATE INDEX realtime_dj_djsession_dj_started_idx ON realtime_dj_djsession (dj_id, started_at DESC);
            CREATE INDEX realtime_dj_djsession_is_live_idx ON realtime_dj_djsession (is_live);
            CREATE INDEX realtime_dj_djsession_station_started_idx ON realtime_dj_djsession (station_id, started_at DESC);
            CREATE INDEX realtime_dj_djtrackinstance_session_deck_idx ON realtime_dj_djtrackinstance (session_id, deck);
            CREATE INDEX realtime_dj_djtrackinstance_session_started_idx ON realtime_dj_djtrackinstance (session_id, started_at DESC);
            CREATE INDEX realtime_dj_audiolevelsnapshot_session_timestamp_idx ON realtime_dj_audiolevelsnapshot (session_id, timestamp DESC);
            CREATE INDEX realtime_dj_audiolevelsnapshot_timestamp_idx ON realtime_dj_audiolevelsnapshot (timestamp DESC);
            CREATE INDEX realtime_dj_djmixerstate_session_updated_idx ON realtime_dj_djmixerstate (session_id, updated_at DESC);
            CREATE INDEX realtime_dj_livestreammetrics_session_timestamp_idx ON realtime_dj_livestreammetrics (session_id, timestamp DESC);
            CREATE INDEX realtime_dj_livestreammetrics_timestamp_idx ON realtime_dj_livestreammetrics (timestamp DESC);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS realtime_dj_djsession_dj_started_idx;
            DROP INDEX IF EXISTS realtime_dj_djsession_is_live_idx;
            DROP INDEX IF EXISTS realtime_dj_djsession_station_started_idx;
            DROP INDEX IF EXISTS realtime_dj_djtrackinstance_session_deck_idx;
            DROP INDEX IF EXISTS realtime_dj_djtrackinstance_session_started_idx;
            DROP INDEX IF EXISTS realtime_dj_audiolevelsnapshot_session_timestamp_idx;
            DROP INDEX IF EXISTS realtime_dj_audiolevelsnapshot_timestamp_idx;
            DROP INDEX IF EXISTS realtime_dj_djmixerstate_session_updated_idx;
            DROP INDEX IF EXISTS realtime_dj_livestreammetrics_session_timestamp_idx;
            DROP INDEX IF EXISTS realtime_dj_livestreammetrics_timestamp_idx;
            """
        ),
    ]
